### ISSUE TITLE
Simplify conditions

### ISSUE THREAD

**Issue by viacheslav-dev-1** [Nikolay0525/UniversityEnvironment#5]
UniversityEnvironment.Data/Model/Tables/TestMark.cs 
` if (value < 2 && value != 0 || value > 5 && value != 0)
                {
                    throw new ArgumentException("Неприпустима оцінка. Оцінка повинна бути 2, 3, 4 або 5.");
                }`

Can we simplify the "if" condition?
Check conditions throughout the project and simplify them if possible

**Comment by Nikolay0525** [comment]
Done
