### ISSUE TITLE
Validation should be outside of data classes and forms

### ISSUE THREAD

**Issue by viacheslav-dev-1** [Nikolay0525/UniversityEnvironment#6]
UniversityEnvironment.Data/Model/Tables/TestMark.cs - Move Mark validation to some Validations.cs file (create a new class with the validation logic) or something else. Validations should be outside of the data classes and forms.

Add more user input validations to prevent users fill incorrect information

**Comment by Nikolay0525** [comment]
Will be done after making a bunch of absent stuff that must be for planned program
