### ISSUE TITLE
Remove repetitive logic

### ISSUE THREAD

**Issue by viacheslav-dev-1** [Nikolay0525/UniversityEnvironment#7]
In UniversityEnvironment.View/Forms/AdminForms/AdminControlForm.cs we have two methods that do a pagination.
```
internal void AdminsRequestUpdate()
        {
            _roleFlag = Role.Admin;
            var query = _context.Admins
                .Where(admin => admin.ForgetPassword == true || admin.Confirmed == false)
                .Skip(_currentPage * Constants.RowsPerPage)
                .Take(Constants.RowsPerPage)
                .OrderBy(admin => admin.Username)
                .Select(admin => new Admin
                {
                    Username = admin.Username,
                    FirstName = admin.FirstName,
                    LastName = admin.LastName,
                    Password = admin.Password,
                })
                .ToList();
            UpdateRequestsTable<Admin>(RequestsTable, query);
        }
```
Can we move the common part of this expression into a generic method?  Also review the similar stuff throughout the project

*** If you have more time, please view the following suggestion:***
Also if we have a big logic in Form event handlers - we can move this logic to Services folder. For example, UserService will handle logic related to admins, teachers, and users. The good practice - is to make Form event handlers simple and clear as possible/

**Comment by Nikolay0525** [comment]
I have some idea, i will try to implement it soon

**Comment by Nikolay0525** [comment]
Done
