### ISSUE TITLE
Repository redundant methods

### ISSUE THREAD

**Issue by viacheslav-dev-1** [Nikolay0525/UniversityEnvironment#8]
Look at the repository at two methods:

```
       public TEntity? FindByFilter(Expression<Func<TEntity, bool>> filter)
        {
            return _objects.FirstOrDefault(filter);
        }

        public TEntity? FindById(Guid id)
        {
            return _objects.Find(id);
        }
```

FindById - it is a partial case of FindByFilter, so we can remove it and use FindByFilter in all cases.

The same is true with Create methods. 
Use `public Task<int> CreateAsync(params TEntity[] entities) {}` to create one or multiple entity (I added here Task to maintain asynchronous operations)

Review all potential places and fix them

**Comment by Nikolay0525** [comment]
Repository is deleted now i have service file, removed redundant methods, but at the moment all work without async

**Comment by Nikolay0525** [comment]
Done
